import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Menu from "./components/Menu";
import "react-toastify/dist/ReactToastify.css";
import "react-loading-skeleton/dist/skeleton.css";

const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "מערכת ציריך",
  description: "Generated by create next app",
};
export const dynamic = "force-dynamic";

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={open_sans.className}>
        <div className="flex text-black max-h-screen  overflow-hidden">
          <Menu />
          <main className=" bg-[rgba(248,248,248,1)] bg-center overflow-y-auto flex-1 h-screen relative">
            <ToastContainer autoClose={1500} />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
